apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  # 'NodePort' es el tipo más simple para exponer un servicio en un solo nodo.
  type: NodePort
  selector:
    # Esto es cómo el servicio encuentra a los pods. Debe coincidir
    # con la etiqueta 'app: frontend' del Deployment.
    app: frontend
  ports:
    - protocol: TCP
      # Puerto que el servicio expone DENTRO del clúster
      port: 80
      # Puerto en el contenedor al que se dirige el tráfico
      targetPort: 80
      # Puerto que se abre en la IP del servidor físico (rango: 30000-32767)
      nodePort: 30080
