apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    # Apunta a los pods con la etiqueta 'app: backend'
    app: backend
  ports:
    - protocol: TCP
      # El puerto del servicio dentro del clúster
      port: 8000
      # El puerto del contenedor al que apunta
      targetPort: 8000
      # ¡Un puerto diferente! Usaremos 30081 para el backend.
      nodePort: 30081
